language: node_js

node_js:
  - "14"

script:
  - npm test
  - npm run build

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: deploy
      node_js: "14"
      script:
        - npm run deploy
