language: node_js

node_js:
  - "6"
  - "7"
  - "8"

script:
  - npm test
  - npm run build

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: deploy
      node_js: "8"
      script:
        - npm run deploy
